### ISSUE TITLE
IndexError: index 250 is out of bounds for axis 0 with size 250,what should I do?

### ISSUE THREAD

**Issue by StephenOlivier** [ffs333/2nd_place_GISLR#1]
## when I run the **"training_notebook_example.ipynb"**,I have an error:
![image](https://github.com/ffs333/2nd_place_GISLR/assets/91003966/37e90e88-b3d2-497f-9aeb-3301373cd103)
### Previously,I do these works:
1. rename bad_weights.npy and the common_weights.npy to data.npy and Y.npy.
2. change the COLAB element from False to True

Apart from it,I wonder if there is a source project to fit the **GISLR_utils**?

**Comment by ffs333** [comment]
1. You should not rename loss weights to data. bad_weights.npy and the common_weights.npy used for loss in losses.py

You can generate data.npy and Y.npy from Kaggle data like this:

```
import os
import numpy as np
import pandas as pd
import json


base_dir = 'data/'  # path to competition data
ROWS_PER_FRAME = 543  # number of landmarks per frame


def load_relevant_data_subset(pq_path):
    data_columns = ['x', 'y', 'z']
    data = pd.read_parquet(pq_path, columns=data_columns)
    n_frames = int(len(data) / ROWS_PER_FRAME)
    data = data.values.reshape(n_frames, ROWS_PER_FRAME, len(data_columns))
    return data.astype(np.float32)


def read_dict(file_path):
    path = os.path.expanduser(file_path)
    with open(path, "r") as f:
        dic = json.load(f)
    return dic


train = pd.read_csv(base_dir + '/train.csv')
label_index = read_dict(f"data/sign_to_prediction_index_map.json")
index_label = dict([(label_index[key], key) for key in label_index])
train["label"] = train["sign"].map(lambda sign: label_index[sign])
print(train.shape)

xyz, Y = [], []

for i in range(len(train)):
    sample = train.loc[i]
    yy = load_relevant_data_subset(base_dir + sample['path'])
    lab = sample['label']

    xyz.append(yy)
    Y.append(lab)

os.makedirs('gen_xyz', exist_ok=True)
np.save('gen_xyz/data.npy', xyz)
np.save('gen_xyz/Y.npy', Y)
```

2. COLAB = True I used only fore Google Colab for copy data from Drive to local storage

**Comment by StephenOlivier** [comment]
I thought the data.py file needed were common_weights.npy and bad_weights.npy.Thanks for answering and Congrats for the 2nd place!
Another things,Could I ask if there is a source project to fit the GISLR_utils?Did you write all this?
> 1. You should not rename loss weights to data. bad_weights.npy and the common_weights.npy used for loss in losses.py
> 
> You can generate data.npy and Y.npy from Kaggle data like this:
> 
> ```
> import os
> import numpy as np
> import pandas as pd
> import json
> 
> 
> base_dir = 'data/'  # path to competition data
> ROWS_PER_FRAME = 543  # number of landmarks per frame
> 
> 
> def load_relevant_data_subset(pq_path):
>     data_columns = ['x', 'y', 'z']
>     data = pd.read_parquet(pq_path, columns=data_columns)
>     n_frames = int(len(data) / ROWS_PER_FRAME)
>     data = data.values.reshape(n_frames, ROWS_PER_FRAME, len(data_columns))
>     return data.astype(np.float32)
> 
> 
> def read_dict(file_path):
>     path = os.path.expanduser(file_path)
>     with open(path, "r") as f:
>         dic = json.load(f)
>     return dic
> 
> 
> train = pd.read_csv(base_dir + '/train.csv')
> label_index = read_dict(f"data/sign_to_prediction_index_map.json")
> index_label = dict([(label_index[key], key) for key in label_index])
> train["label"] = train["sign"].map(lambda sign: label_index[sign])
> print(train.shape)
> 
> xyz, Y = [], []
> 
> for i in range(len(train)):
>     sample = train.loc[i]
>     yy = load_relevant_data_subset(base_dir + sample['path'])
>     lab = sample['label']
> 
>     xyz.append(yy)
>     Y.append(lab)
> 
> os.makedirs('gen_xyz', exist_ok=True)
> np.save('gen_xyz/data.npy', xyz)
> np.save('gen_xyz/Y.npy', Y)
> ```
> 
> 2. COLAB = True I used only fore Google Colab for copy data from Drive to local storage

**Comment by ffs333** [comment]
> I thought the data.py file needed were common_weights.npy and bad_weights.npy.Thanks for answering and Congrats for the 2nd place!
> 
> Another things,Could I ask if there is a source project to fit the GISLR_utils?Did you write all this?
> 
> > 1. You should not rename loss weights to data. bad_weights.npy and the common_weights.npy used for loss in losses.py
> 
> > 
> 
> > You can generate data.npy and Y.npy from Kaggle data like this:
> 
> > 
> 
> > ```
> 
> > import os
> 
> > import numpy as np
> 
> > import pandas as pd
> 
> > import json
> 
> > 
> 
> > 
> 
> > base_dir = 'data/'  # path to competition data
> 
> > ROWS_PER_FRAME = 543  # number of landmarks per frame
> 
> > 
> 
> > 
> 
> > def load_relevant_data_subset(pq_path):
> 
> >     data_columns = ['x', 'y', 'z']
> 
> >     data = pd.read_parquet(pq_path, columns=data_columns)
> 
> >     n_frames = int(len(data) / ROWS_PER_FRAME)
> 
> >     data = data.values.reshape(n_frames, ROWS_PER_FRAME, len(data_columns))
> 
> >     return data.astype(np.float32)
> 
> > 
> 
> > 
> 
> > def read_dict(file_path):
> 
> >     path = os.path.expanduser(file_path)
> 
> >     with open(path, "r") as f:
> 
> >         dic = json.load(f)
> 
> >     return dic
> 
> > 
> 
> > 
> 
> > train = pd.read_csv(base_dir + '/train.csv')
> 
> > label_index = read_dict(f"data/sign_to_prediction_index_map.json")
> 
> > index_label = dict([(label_index[key], key) for key in label_index])
> 
> > train["label"] = train["sign"].map(lambda sign: label_index[sign])
> 
> > print(train.shape)
> 
> > 
> 
> > xyz, Y = [], []
> 
> > 
> 
> > for i in range(len(train)):
> 
> >     sample = train.loc[i]
> 
> >     yy = load_relevant_data_subset(base_dir + sample['path'])
> 
> >     lab = sample['label']
> 
> > 
> 
> >     xyz.append(yy)
> 
> >     Y.append(lab)
> 
> > 
> 
> > os.makedirs('gen_xyz', exist_ok=True)
> 
> > np.save('gen_xyz/data.npy', xyz)
> 
> > np.save('gen_xyz/Y.npy', Y)
> 
> > ```
> 
> > 
> 
> > 2. COLAB = True I used only fore Google Colab for copy data from Drive to local storage
> 
> 
> 
> 

Thanks.
Yes, this project written by my team and I.
